/*
Navicat MySQL Data Transfer

Source Server         : Pridefire
Source Server Version : 50500
Source Host           : localhost:3306
Source Database       : world

Target Server Type    : MYSQL
Target Server Version : 50500
File Encoding         : 65001

Date: 2010-12-09 11:33:53
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for `db_script_string`
-- ----------------------------
DROP TABLE IF EXISTS `db_script_string`;
CREATE TABLE `db_script_string` (
  `entry` int(11) unsigned NOT NULL DEFAULT '0',
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of db_script_string
-- ----------------------------
INSERT INTO `db_script_string` VALUES ('2000000001', 'Get in the Ring of Blood, $N. The fight is about to start!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000002', 'The battle is about to begin!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000003', '$N versus the ferocious clefthoof, Brokentoe!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000009', 'What happens?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000010', 'Volcor need help ?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000011', 'All right, I shall find people to help him.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000012', 'All right, let\'s go.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000013', 'Oh no! They a here!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000014', 'Oh, hello Grimclaw.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000015', 'Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000016', 'Ok, good luck friend. Thanks for the help.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000017', 'Ok, let\'s go!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000018', 'I can make it the rest of the way. $N. THANKS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000019', 'Be patient $N. The torch is almost complete.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000020', 'That\'s interesting...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000021', 'I need to consult Noram and Horatio.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000022', 'Look! Minions of Terokk are approaching!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000023', 'Look out! More are coming!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000024', 'And even more!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000025', 'An Avatar of Terokk! To arms!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000026', 'Whoops!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000029', 'Follow, $N. I will soon begin the summoning...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000030', 'This makes sense!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000031', 'Your body is mine! Our fates are forever intertwined!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000032', 'Gird yourself $N, for the demon in this orb is a fel beast.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000033', 'Keep moving!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000034', 'Come, $N. Lord Stormrage awaits.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000035', 'Warriors of Dragonmaw, gather \'round! One among you has attained the rank of highlord! Bow your heads in reverence! Show your respect and allegiance to Highlord $N!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000036', 'Lord Illidan will be here shortly.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000037', 'All hail Lord Illidan!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000038', 'Lord Illidan, this is the Dragonmaw that I, and others, have told you about. He will lead us to victory!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000039', 'But... My lord, I do not understand. $N... He is the orc that has...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000040', 'It will be done, my lord.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000041', 'So you thought to make a fool of Mor\'ghor, eh? Before you are delivered to Lord Illidan, you will feel pain that you could not know to exist. I will take pleasure in exacting my own vengeance.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000042', 'Until we meet again, brave one.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000043', 'begins a spell of summoning...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000044', 'It is done...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000045', 'There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000046', 'Oooooo hot hot hot! If that won\'t put spring in your step, I don\'t know what will!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000047', 'Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000048', 'Now let us place this rare earth in my planter...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000049', 'Thank you again, $N. This rare earth will be very helpful in my experiments.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000050', 'Hello Grimclaw', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000051', 'What happens?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000052', 'Volcor was gone?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000053', 'You know where he is?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000054', 'Well, ok. I am now sending people . We need find and help him.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000055', 'How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000056', 'Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000057', 'Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000058', 'Thank you great spirit. Thank you!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000059', 'You are Dismissed, $N', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000060', 'By the stars! A spirit has been summoned!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000061', 'It\'s a mystery of the past indeed! But a key to our future!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000062', 'The threat be over! $N be savin\' us all!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000063', 'Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000064', 'Well, that should do it. Come now, back to the shop to finish our business!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000065', 'We will suffer no demon\'s servant in our lands!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000066', 'Peace and patience be with you, $N. Remain strong always.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000067', 'What are you doing in Ysera\'s realm, interloper? Leave us, I say! Your kind are not welcome here!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000068', 'You -- you\'re not one of them! Let\'s get out of sight before they find us! Hurry!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000069', 'They\'re following me, $R! Quickly, tell me why you\'re here before we\'re discovered! If they catch up to me, it will mean my death and yours!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000070', 'It would\'ve taken years to find the Book of the Raven without you, young sparrowhawk. Return to your home in Nagrand with our gratitude.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000071', 'This is it! This is really it -- the Book of the Raven!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000072', 'It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000073', 'There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000074', 'The tablet has the confirmation we need, just as I thought. Now, we have to use this information to draw out and defeat this Anzu before he can do any more damage to the Emerald Dream!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000075', 'Since the sparrowhawks have proven such a success in hunting down the raven stones, Watcher Elaira has trained another one to relay my voice at a great distance. He can help us communicate as you investigate the bird spirits revealed in the tablet!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000076', 'Hear ye, denizens of Tanaris! Let it be known $n is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $n!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005000', 'Poor Dorius. If I ever get my hands on those Dark Irons, so help me...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005001', 'Opus wants some Cuergo\'s Gold... with worm.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005002', 'Bijou lost! SQUAWK! *cough', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005003', 'Kibler is being investigated by G.E.T.A.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005004', 'Bijou knows where treasures are hidden.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005005', 'Dragons controlling orcs!? SQUAWK!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005006', 'They all go to the Spire but none never come back... just like Bijou.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005007', 'Ask Kibler about the treasure! SQUAWK!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005008', 'SQUAWK!! *cough* *cough* I need to quit smoking!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005009', 'Well done, soldiers! At ease!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005010', 'Zug zug! Happy to help!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005011', 'Yes right away momma!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005012', 'Mysterious hoofprints, scorched shields, stray badges... how do we make sense of all this?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005013', 'I don\'t think Drazzit\'s going to have any luck finding anyone to kill this raptor. I mean, he\'s already raised the reward twice...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005014', 'But this the only building that fit Brogg! Goblins make buildings too small!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005015', 'I thought we talked about this, Brogg. You can\'t stay in this building. Sure, it can house you, but there\'s no room for anyone else!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005016', 'Yes, we said you can stay here, but this building is our headquarters! All of our manuals and blueprints are stored here!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005017', 'I\'m inclined to say they made ogres too big! I can see I\'m not going to convince you to move now, but don\'t think this is permanent!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005018', 'Ah, this must be him now... no?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005019', 'You might wanna stand back. Fish guttin\' is a dirty job.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005020', 'It\'s good to see you defending Theramore with pride, friend.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005021', 'When you\'re off duty, let\'s go to the inn. I\'ll buy a round and we can reminisce about the good old days.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005022', 'Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005023', 'Every item that I have for sale I acquired myself. You have my personal guarantee of authenticity.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005024', 'It\'s getting away!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005025', 'Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005026', 'Come speak with me, and what once was cloudy shall become crystal clear.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005027', 'The Lich King\'s forces are building. It is imperative that our timetable supports his plans.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005028', 'Tomorrow we will begin training of our promising dragons, so don\'t forget your chew toys.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005029', 'Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005030', 'If you wait to come see me, there may be nothing left!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005031', 'I come from the land down under... where women plague and men sunder.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005032', '...And then the tauren said, \"13 INCHES!\"', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005033', 'Come one, come all! Welcome to the Darkmoon Faire! Do you crave adventure? Do you seek exotic and mysterious treasures? Then look no further! You, my friend, have come to the right place! Dive right in and take part in all that the Faire has to offer! We\'ll be at this location all week, so be sure to tell your friends and loved ones!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005034', 'Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005035', 'It\'s getting away!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005036', 'Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005037', 'I might just have to go hunting for that Wretched beast now that there\'s a bounty on his head.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005038', 'Tell us! Where does you leader hide?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005039', 'The wind speaks of our enemies\' movements, Ashyen. The Naga will attack again.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005040', 'Very well. When that decision is made, I will be ready. Let us hope it won\'t be too late.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005041', 'I will do my best to take care of the children, Grandmother.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005042', 'New posting up! Adventurers and heroes, gather round the bulletin board!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005043', 'I WILL DESTROY ALL', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005044', 'US ALREADY ALL ANYMORE AND ANYMORE', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005045', 'Just don\'t ask me where I got it...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005046', 'I\'m up to looking into that bounty after this shift.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005047', 'You want to go do the bounty off of this wanted poster after this shift is over?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005048', 'Having a good time?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005049', 'I have another reading from the nether.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005050', 'Well hand it overand let\'s see what you got!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005051', 'Great Gazlowe!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005052', 'Hey, you there. Want some candy?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005053', 'Bip!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005054', 'Bip!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005055', 'Bip!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005056', 'Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005057', 'Crybaby! Crybaby!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005058', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005059', 'I wonder if your dolly can swim!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005060', 'Ha ha! I have Betsy!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005061', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005062', 'I have your dolly! Nyah nyah!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005063', 'Crybaby! Crybaby!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005064', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005065', 'I wonder if your dolly can swim!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005066', 'Ha ha! I have Betsy!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005067', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005068', 'I have your dolly! Nyah nyah!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005069', 'Crybaby! Crybaby!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005070', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005071', 'I wonder if your dolly can swim!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005072', 'Ha ha! I have Betsy!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005073', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005074', 'I have your dolly! Nyah nyah!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005075', 'Crybaby! Crybaby!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005076', 'Baby wants her dolly!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005077', 'I wonder if your dolly can swim!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005078', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005079', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005080', 'Don\'t hurt Betsy, you meanie!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005081', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005082', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005083', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005084', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005085', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005086', 'Don\'t hurt Betsy, you meanie!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005087', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005088', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005089', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005090', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005091', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005092', 'Don\'t hurt Betsy, you meanie!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005093', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005094', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005095', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005096', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005097', 'Gimmie my dolly!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005098', 'Don\'t hurt Betsy, you meanie!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005099', 'Fresh bread for sale', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005100', 'Get it while its hot', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005101', 'Fresh bread for sale', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005102', 'Get it while its hot', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005103', 'Jack and Jill my wrinkled patoot! I do all the water luggin round here.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005104', 'Wheres the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldnt know what water looks like.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005105', 'Of Course Im talking to myself. Only way to get a decent conversation in this city.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005106', 'As if I dont have better things to do in my old age than carry buckets of water.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005107', 'Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005108', 'Deja vu. For a moment I thought I was back home... before the plague...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005109', 'They say he can turn into a raven sometimes.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005110', 'They say he can turn into a raven sometimes.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005111', 'And then the rabbit just bit his head off... I swear.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005112', 'I swear, people have actualy seen them. Pandaren really do exist!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005113', 'You know why Orcs eyes glow red? It\'s because they drink blood!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005114', 'I dont think there\'s any fish in these canals.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005115', 'And that\'s how Lother killed thirty six orcs with his bare hands!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005116', 'Eww... that\'s not a fish!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005117', 'I got worm guts on my shoes.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005118', 'I think i see something.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005119', 'Eww... that\'s not a fish!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005120', 'I think i see something.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005121', 'I hope that was a fish!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005122', 'Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005123', 'Can you imagine?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005124', 'Really?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005125', 'Wow.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005126', 'My father says that\'s just a story.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005127', 'Really?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005128', 'Wow.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005129', 'That\'s neat.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005130', 'Wow.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005131', 'Really?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005132', 'Look alive, dogs! We got an operation to run here!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005133', 'Having a good time?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005134', 'Here we have the Cathedral of Light, the center of spiritual enlightenment here in Stormwind.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005135', 'Yes, that is true. Paladins and Priests alike train their skills and research great truths behind the walls of the Cathedral.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005136', 'Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005137', 'Here we have Stormwind Keep. Built upon the ruins of Stormwind Castle, which was destroyed by the Horde in the first Great War.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005138', 'When the Horde was shattered, men returned here and began to rebuild the once great city as a testament to our own survival.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005139', 'Yes, well...let\'s head on to the monument dedicated to the heroes of the two Great Wars, the Valley of Heroes. Follow Me.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005140', 'Isn\'t it amazing, children? All who enter the city must walk beneath the watchful eyes of the greatest heroes of our lands.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005141', 'Breathtaking. Children, when we return to the school, you will each give an oral report on one of these legendary people.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005142', 'Now, take another long look before we make our way to the Holy District and the great Cathedral of Light.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005143', 'This will never do..', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005144', 'This must be fixed!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005145', 'How can anyone live like this!?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005146', 'Duck!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005147', 'Don\'t go close to the lake! It\'s haunted!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005148', 'Putting in twelve centers of focus might allow the magical energies to form more solidly, adding the necessary stability.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005149', 'At least we would not be around to have to clean it up.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005150', 'Only if we did not follow the proper initialization procedures.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005151', 'The resultant energies could collapse though, and that could cause an energy flux that would give you a migraine for weeks.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005152', 'Only if we did not follow the proper initialization procedures.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005153', 'Only if we did not follow the proper initialization procedures.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005154', 'At least we would not be around to have to clean it up.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005155', 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005156', 'I suppose that could work, if we had twenty people to cast it with.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005157', 'But what if the resulting frequency shift were to send magical feedback up the flows?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005158', 'When the positively aligned energies collide with the negatively charged energies, they don`t negate one another.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005159', 'That will unbalance the magical focus, though, and cause a reverse vibration in the ether.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005160', 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005161', 'Why can\'t we just shift the array to compensate for the variance in the flux?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005162', 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005163', 'I think not, I don\'t need to be blown up again.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005164', 'Maginor says that twisting alternating flows of positive energy actually creates a much more stable flow.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005165', 'But wouldn`t that mean crossing the streams? Isn`t that really bad?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005166', 'But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005167', 'Is it true that the paladins train here?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005168', 'Why do we have to learn this stuff anyway?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005169', 'If we reverse the Essence flows perhaps we can alter the polarity.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005170', 'What if we used three focuses in Tyrean pattern? That should solve it.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005171', 'Wow, all this for a love potion. Hope he is worth it.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005172', 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005173', 'The Portal will shift slightly. At this point if you cast a binding cantrip you will solidify it in place.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005174', 'Wow, all this for a love potion. Hope he is worth it.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005175', 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005176', 'What if we used three focuses in Tyrean pattern? That should solve it.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005177', 'If we use the appropriate sequence we should be ok. Will just take some serious studying before we start.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005178', 'But if we stabilize it with an anchor thread at the appropriate energy crux then it should work.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005179', 'Wow, all this for a love potion. Hope he is worth it.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005180', 'Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005181', 'Sure Paige. Just be gentle.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005182', 'Thanks, Charys. C\'mon Paige, sweetie.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005183', 'Mommy? Can I pet Fizzles?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005184', 'Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005185', 'Magical studies stressing your brain? Relax at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005186', 'Best drinks in Stormwind!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005187', 'Head on over to the Blue Recluse. Where everybody knows your name!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005188', 'Feeling blue? Come on down to the Blue Recluse for a good time!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005189', 'Best drinks in Stormwind!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005190', 'Magical studies stressing your brain? Relax at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005191', 'Ask me how you can get a free drink at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005192', 'Head on over to the Blue Recluse. Where everybody knows your name!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005193', 'Free drinks at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005194', 'Feeling blue? Come on down to the Blue Recluse for a good time!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005195', 'Magical studies stressing your brain? Relax at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005196', 'Best drinks in Stormwind!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005197', 'Ask me how you can get a free drink at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005198', 'Head on over to the Blue Recluse. Where everybody knows your name!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005199', 'Best drinks in Stormwind!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005200', 'Charge!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005201', 'Charge!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005202', 'Ahh, my precious Ameenah! How wonderful to see you again.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005203', 'Yer wearin down, princess, I can sense it!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005204', 'Hmm, don\'t mind if I do!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005205', 'It\'s coming along, Wafflefry. Haven\'t you got a product demonstration to do or something?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005206', 'Be the first on your block to own the incredible Electrostatic Maculation Blaster!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005207', 'Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005208', 'Wine stains, grass stains, even pet stains are no match for the Electrostatic Maculation Blaster!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005209', 'Don\'t wait! Order now and receive my Ultra-Kinetic Waffle Iron at no additional charge!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005210', 'I\'ll never stop. Never...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000077', 'Ah, that sure does hit the spot! I think i\'ll get myself a couple more...can you watch these barrels for me, $N?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000078', 'How goes the barrel watching...?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000079', 'Well, back to business for me. But it sure was nice taking that short break, and it\'s always nice drinking Thunder Ale!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000080', 'This shouldn\'t take long...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000081', 'The invisibility liquer is ready for you, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005237', 'These fires have been burning steadily for years. Unusual dedication for trolls.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005238', 'Strange... These mosaics don\'t resemble any known troll traditions.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005239', 'Yes, yes, I\'m quite certain this represents the melding of entities. Fascinating.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005240', 'One can learn volumes about a culture by studying its refuse.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005241', 'Ugh. Matted clumps of hair, molted feathers, bits of bone, partially burned material - clothing perhaps?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000093', 'Denalan hurries to his planter.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000094', 'I hope this frond takes root...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000082', 'I. . .I. . .don\'t. . .feel. . .right. . .', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000083', 'My mind. . .my flesh. . .I\'m. . .rotting. . . .!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000084', 'I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000085', 'Take a Candle of Beckoning from this crate, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000090', 'Onu studies the parchment from the Twilight Tome...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000091', 'Onu is struck by unleashed magic!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000092', 'Hmm...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000086', 'Denalan removes the seeds from the Glowing Fruit...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000087', 'Let\'s see how these seeds grow in my prepared soil...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000088', 'Denalan plants fruit seeds.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000089', 'Bogling rises from the soil!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000008', 'Make haste, $N. Use the portal!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000105', 'The spirits of Stonetalon still rage, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000106', 'I fear we may never soothe them...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000028', 'The People of Westfall salute $N, a brave and valiant defender of freedom.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000095', 'Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000096', 'The Water of the Seers is ready for your consumption, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000097', 'Tonga Runetotem inspects the snapjaw shells...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000098', 'Hm...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000099', 'Strange. Very strange...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000100', '$N. These shells tell me much, but I fear many more questions are now raised...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000101', 'Ok, let\'s take a look at this thing...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000102', 'Oh, darn...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000103', 'Ok, let\'s get started!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000104', '... oops.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005400', 'We really should fix this fence soon.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005401', '*sigh* It\'s about time to check on the cemetary again-- Ill be back in a few minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005402', 'How long can it take to pick a handful of weeds?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005403', 'At this rate I could have gathered them myself!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005404', 'Ah, this must be him now... no? Bah!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005405', 'As if I had all eternity.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005406', 'We\'re running low on iron, lads! I don\'t want to see a single bar go to waste, ye hear me now?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005407', 'Not bad. Try that trick I told you about when you temper the steel.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000004', 'These tracks must belong to Shango.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000005', 'These aren\'t Shango\'s tracks.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000138', 'I hereby destroy these instruments of evil! For the Horde!', null, null, null, null, null, null, null, null);
